# Juego de palabras

partecuerpo = input("Parte del cuerpo(Plural): ")
adjetivoplural = input("Adjetivo masculino(Plural): ")
adjetivo = input("Adjetivo masculino: ")
adjetivo2 = input("Adjetivo masculino: ")
lugar = input("Lugar :")
animal = input("Animal: ")
partecuerpo2 = input("Parte del cuerpo(Singular): ")
adjetivo3 = input("Adjetivo: ")
adjetivoplural2 = input("Adjetivo femenino(Plural): ")
adverbio = input("Adverbio :")
interjeccion = input(("Interjeccion: "))
adjetivoplural3 = input("Adjetivo femenino(Plural): ")
nombre = input(("Nombre propio: "))
nombre2 = input("Nombre femenino: ")

print(f"Antiguamente, el ser humano caminaba a cuatro {partecuerpo},")
print(f"se expresaba mediante gruñidos {adjetivoplural} y no sabia encender")
print(f"un {adjetivo} fuego. Esta es la historia del dia en que la humanidad")
print(f"cambio para siempre(traducida del {adjetivo2} idioma de las cavernas):")
print("Hombre de las cavernas 1: En esta cueva hace mas fio que en (el/la)")
print(f"{lugar} .Incluso con la piel del/de la {animal} mas caliente no")
print(f"consigo que mi {partecuerpo2} deje de tiritar.")
print("Hombre de las cavernas 2: Si al menos pudiesemos encontrar una")
print(f"manera de que el frio fuera mas {adjetivo3}.")
print("Hombre de las cavernas 1: Estoy aburrido. Creo que voy a jugar un")
print(f"rato con estas ramas {adjetivoplural2}.")
print(f"Hombre de las cavernas 2:¿Por que no las frotas {adverbio} a ver")
print("qué pasa?")
print(f"Hombre de las cavernas 1: ¡{interjeccion}! Esta saliendo humo de")
print(f"las {adjetivoplural3} ramas!")
print("Hombre de las cavernas 2: ¡Ay! ¡Está caliente! ¡Por el amor de")
print(f"{nombre} hemos conseguido calor!")
print("Hombre de las cavernas 1: A partir de ahora, llamaremos \"fuego\" a esta")
print(f"{nombre2}magica.")




